build-windows:
  runs-on: windows-latest

  steps:
  - uses: actions/checkout@v2
  
  - name: Set up Flutter
    uses: subosito/flutter-action@v2

  - name: Install dependencies
    run: flutter pub get

  - name: Enable windows
    run: flutter config --enable-windows-desktop

  - name: Build Windows application
    run: flutter build windows